- name: copy kubernetes secrets
  template:
    src: prometheus-additional.yaml.j2
    dest: "{{ k8s_secret_path }}/{{ scrape_secret_name_file }}"
    mode: 0600
  register: k8s_secrets

- name: Apply Secret manifest to the cluster.
  kubernetes.core.k8s:
    state: present
    src: "{{ k8s_secret_path }}/{{ scrape_secret_name_file }}"