---
- name: Read certificate
  ansible.builtin.debug:
    var: item
    verbosity: 3
  with_file:
    - node_exporter.crt
  register: cert

- name: print certificate
  become: false
  ansible.builtin.template:
    src: tls-secret.yaml.j2
    dest: "{{ k8s_secret_path }}/{{ tls_secret_name_file }}"
    mode: 0600

- name: Apply TLS secret manifest to the cluster.
  become: false
  kubernetes.core.k8s:
    state: present
    src: "{{ k8s_secret_path }}/{{ tls_secret_name_file }}"